# Generated by Django 4.2.6 on 2023-10-17 18:35

import django.core.validators
from django.db import migrations, models
import pessoa.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_pessoa', models.CharField(choices=[('1', 'Pessoa Fisica'), ('2', 'Pessoa Juridica')], max_length=1)),
                ('cnpj_cpf', models.CharField(max_length=18, validators=[pessoa.validators.validar_cnpj_cpf])),
                ('rg_ie', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15, validators=[pessoa.validators.validar_telefone])),
                ('celular', models.CharField(max_length=15, validators=[pessoa.validators.validar_telefone])),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator(message='Informe um email valido')])),
                ('cliente', models.BooleanField()),
                ('vendedor', models.BooleanField()),
                ('transportadora', models.BooleanField()),
                ('fornecedor', models.BooleanField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
