# Generated by Django 4.2.6 on 2023-10-17 19:04

from django.db import migrations, models
import pessoa.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_alter_pessoa_cliente_alter_pessoa_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, validators=[pessoa.validators.validar_telefone]),
        ),
    ]
