# Generated by Django 4.2.6 on 2023-10-28 19:39

from django.db import migrations, models
import pessoa.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_alter_pessoa_data_nascimento_alter_pessoa_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cnpj_cpf',
            field=models.CharField(max_length=18, validators=[pessoa.validators.validar_cnpj_cpf]),
        ),
    ]
